import type { NextPage } from 'next';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import { END } from 'redux-saga';

import { followingPostsRequest } from '../../actions/post/following-posts.action';
import { getFollowingsRequest } from '../../actions/user/get-followings.action';
import { Aside } from '../../components/layout/Aside';
import { Main } from '../../components/layout/Main';
import { MainTitle } from '../../components/layout/Main.style';
import { SearchFollowing } from '../../components/partitial/aside/SearchFollowing';
import { PostItem } from '../../components/PostItem';
import { ScrollList } from '../../components/ScrollList';
import { AppState } from '../../reducers';
import { PostState } from '../../reducers/post';
import { wrapper } from '../../store';

const Follow: NextPage = () => {
    const { followingPosts } = useSelector<AppState, PostState>(
        (state) => state.post,
    );

    return (
        <>
            <Head>
                <title>Following</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <MainTitle>
                    <h2>팔로잉 최신 포스트</h2>
                </MainTitle>
                <ScrollList
                    {...followingPosts}
                    actionCreator={followingPostsRequest}
                    Node={PostItem}
                />
            </Main>
            <Aside>
                <MainTitle>
                    <h2>팔로잉 목록</h2>
                </MainTitle>
                <SearchFollowing />
            </Aside>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    ({ dispatch, sagaTask }) =>
        async ({ req, res, query, ...etc }) => {
            const { userId, search } = query;

            // if (userId && typeof userId !== 'string') {
            //     res.statusCode = 302;

            //     res.setHeader('Location', '/404');
            // }

            dispatch(
                getFollowingsRequest({
                    limit: 5,
                    nickname: search as string | undefined,
                }),
            );

            dispatch(
                followingPostsRequest({
                    limit: 10,
                    userId: userId as string | undefined,
                }),
            );

            dispatch(END);

            await sagaTask?.toPromise();

            return {
                props: {},
            };
        },
);

export default Follow;
