import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { END } from 'redux-saga';
import { Aside } from '../../components/layout/Aside';
import { Main } from '../../components/layout/Main';
import { MainTitle } from '../../components/layout/Main.style';
import { wrapper } from '../../store';

const Follow: NextPage = () => {
    const dispatch = useDispatch();

    return (
        <>
            <Head>
                <title>Following</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <MainTitle>
                    <h2>팔로잉 최신 포스트</h2>
                </MainTitle>
            </Main>
            <Aside></Aside>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    ({ getState, dispatch, sagaTask }) =>
        async ({ req, res, ...etc }) => {
            const { user, post, category } = getState();

            // if (post.homePosts.pageInfo === null) {
            //     dispatch(
            //         homePostsRequest({
            //             limit: 12,
            //         }),
            //     );
            // }

            dispatch(END);

            await sagaTask?.toPromise();

            return {
                props: {},
            };
        },
);

export default Follow;
