import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { useSelector } from 'react-redux';
import { END } from 'redux-saga';
import styled from 'styled-components';

import { userPostsRequest } from '../../actions/post/user-posts.action';
import { getUserRequest } from '../../actions/user/get-user.action';
import { Aside } from '../../components/layout/Aside';
import { Main } from '../../components/layout/Main';
import { MainTitle } from '../../components/layout/Main.style';
import { PostItem } from '../../components/PostItem';
import { RectangleAvatar } from '../../components/RectangleAvatar';
import { mixinBox } from '../../components/theme/mixins';
import { UploadAvatar } from '../../components/UploadAvatar';
import { AppState } from '../../reducers';
import { PostState } from '../../reducers/post';
import { UserState } from '../../reducers/user';
import { wrapper } from '../../store';

const UserProfileContainer = styled.div`
    position: relative;
    margin-bottom: 20px;

    ${mixinBox}
`;

const UserProfileHeader = styled.div`
    position: relative;
    min-height: 186px;
    height: 0;
`;

const UserProfile: NextPage = () => {
    const { userPosts } = useSelector<AppState, PostState>(
        (state) => state.post,
    );

    const { id, avatar, userPageProfile } = useSelector<AppState, UserState>(
        (state) => state.user,
    );

    const [uploadedFile, setUploadedFile] = useState<string>(
        userPageProfile!.avatar,
    );

    const isMe = id == userPageProfile?.id;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <MainTitle>
                    <h2>모든 포스트</h2>
                </MainTitle>
                {userPosts.nodes.map((post) => (
                    <PostItem key={`"userPost${post.id}`} {...post} />
                ))}
            </Main>
            <Aside>
                <UserProfileContainer>
                    <UserProfileHeader>
                        {isMe ? (
                            <UploadAvatar
                                src={avatar!}
                                setUploadedFile={setUploadedFile}
                            />
                        ) : (
                            <RectangleAvatar
                                src={userPageProfile!.avatar}
                                alt="Avatar"
                            />
                        )}
                    </UserProfileHeader>
                </UserProfileContainer>
            </Aside>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    ({ dispatch, sagaTask }) =>
        async ({ req, res, query, ...etc }) => {
            try {
                if (!query.id) {
                    throw new Error(
                        '[Next] access denied in userPage:getServerSideProps',
                    );
                }

                const id = query.id as string;

                dispatch(
                    getUserRequest({
                        id,
                    }),
                );

                dispatch(
                    userPostsRequest({
                        limit: 10,
                        userId: id,
                    }),
                );

                dispatch(END);

                await sagaTask?.toPromise();
            } catch (e) {
                console.log((e as Error).message);

                res.statusCode = 302;

                res.setHeader('Location', '/');
            }

            return {
                props: {},
            };
        },
);

export default UserProfile;
