import type { NextPage } from 'next';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import { END } from 'redux-saga';

import { Aside } from '../../components/layout/Aside';
import { Main } from '../../components/layout/Main';
import { MainTitle } from '../../components/layout/Main.style';
import { PostItem } from '../../components/PostItem';
import { AppState } from '../../reducers';
import { PostState } from '../../reducers/post';
import { wrapper } from '../../store';
import { ScrollList } from '../../components/ScrollList';
import { searchPostsRequest } from '../../actions/post/search-posts.action';

interface Props {
    searchKeyword: string;
}

const Search: NextPage<Props> = ({ searchKeyword }) => {
    const { searchPosts } = useSelector<AppState, PostState>(
        (state) => state.post,
    );

    return (
        <>
            <Head>
                <title>검색 결과</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <MainTitle>
                    <h2>{`"${searchKeyword}"와 관련된 포스트 목록`}</h2>
                </MainTitle>
                <ScrollList
                    {...searchPosts}
                    actionCreator={searchPostsRequest}
                    Node={PostItem}
                    payload={{ searchKeyword }}
                />
            </Main>
            <Aside></Aside>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    ({ dispatch, sagaTask }) =>
        async ({ req, res, query, ...etc }) => {
            const searchKeyword = query.keyword as string;

            dispatch(
                searchPostsRequest({
                    limit: 12,
                    searchKeyword,
                }),
            );

            dispatch(END);

            await sagaTask?.toPromise();

            return {
                props: {
                    searchKeyword,
                },
            };
        },
);

export default Search;
